COMPANY_SEED: list[dict[str, str]] = [
    {"board_token": "stripe", "company_name": "Stripe"},
    {"board_token": "vercel", "company_name": "Vercel"},
    {"board_token": "figma", "company_name": "Figma"},
    {"board_token": "linear56", "company_name": "Linear"},
    {"board_token": "airbnb", "company_name": "Airbnb"},
    {"board_token": "netflix", "company_name": "Netflix"},
    {"board_token": "spotify", "company_name": "Spotify"},
    {"board_token": "shopify", "company_name": "Shopify"},
    {"board_token": "notion", "company_name": "Notion"},
    {"board_token": "datadog81", "company_name": "Datadog"},
    {"board_token": "plaid", "company_name": "Plaid"},
    {"board_token": "squarespace", "company_name": "Squarespace"},
    {"board_token": "twilio", "company_name": "Twilio"},
    {"board_token": "coinbase", "company_name": "Coinbase"},
    {"board_token": "brex", "company_name": "Brex"},
    {"board_token": "retool35", "company_name": "Retool"},
    {"board_token": "watershed", "company_name": "Watershed"},
    {"board_token": "ramp", "company_name": "Ramp"},
    {"board_token": "lattice", "company_name": "Lattice"},
    {"board_token": "airtable", "company_name": "Airtable"},
    {"board_token": "dbtlabs", "company_name": "dbt Labs"},
    {"board_token": "loom", "company_name": "Loom"},
    {"board_token": "mux", "company_name": "Mux"},
    {"board_token": "planetscale", "company_name": "PlanetScale"},
    {"board_token": "supabase", "company_name": "Supabase"},
    {"board_token": "clerk", "company_name": "Clerk"},
    {"board_token": "resend", "company_name": "Resend"},
    {"board_token": "railway", "company_name": "Railway"},
    {"board_token": "render", "company_name": "Render"},
    {"board_token": "sentry", "company_name": "Sentry"},
    {"board_token": "hashicorp", "company_name": "HashiCorp"},
    {"board_token": "postman", "company_name": "Postman"},
    {"board_token": "grafana", "company_name": "Grafana Labs"},
    {"board_token": "atlassian", "company_name": "Atlassian"},
    {"board_token": "gitlab", "company_name": "GitLab"},
    {"board_token": "contentful", "company_name": "Contentful"},
    {"board_token": "sanity", "company_name": "Sanity"},
    {"board_token": "storybook", "company_name": "Storybook / Chromatic"},
    {"board_token": "webflow", "company_name": "Webflow"},
    {"board_token": "framer", "company_name": "Framer"},
    {"board_token": "amplitude", "company_name": "Amplitude"},
    {"board_token": "segment", "company_name": "Segment"},
    {"board_token": "launchdarkly", "company_name": "LaunchDarkly"},
    {"board_token": "gusto", "company_name": "Gusto"},
    {"board_token": "rippling", "company_name": "Rippling"},
    {"board_token": "deel", "company_name": "Deel"},
    {"board_token": "mercury", "company_name": "Mercury"},
    {"board_token": "nerdwallet", "company_name": "NerdWallet"},
    {"board_token": "affirm", "company_name": "Affirm"},
]
